apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  labels:
    app.kubernetes.io/name: mosquitto
data:
  mosquitto.conf: |
    # Mosquitto configuration file
    
    # General settings
    persistence true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
    log_dest stdout
    
    # MQTT listener on port 1883
    listener 1883
    protocol mqtt
    
    # WebSocket listener on port 9001
    listener 9001
    protocol websockets
    
    # Authentication - default allows anonymous
    allow_anonymous true
    
    # Logging
    log_type error
    log_type warning
    log_type notice
    log_type information
    
    # Connection messages
    connection_messages true
