apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mosquitto-websocket
  labels:
    app.kubernetes.io/name: mosquitto
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    gethomepage.dev/description: MQTT Message Broker
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: sh-mosquitto
    gethomepage.dev/name: Mosquitto
    gethomepage.dev/pod-selector: app.kubernetes.io/name=mosquitto
spec:
  ingressClassName: internal
  tls:
    - hosts:
      - mqtt.internal.gustend.net
      secretName: mqtt-internal-gustend-net-cert
  rules:
    - host: mqtt.internal.gustend.net
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: mosquitto
                port:
                  number: 9001
