apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: komga
  labels:
    app.kubernetes.io/name: komga
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    gethomepage.dev/description: Comic and Manga Server
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Media
    gethomepage.dev/icon: sh-komga
    gethomepage.dev/name: Komga
    gethomepage.dev/pod-selector: app.kubernetes.io/name=komga
spec:
  ingressClassName: internal
  tls:
    - hosts:
      - komga.internal.gustend.net
      secretName: komga-internal-gustend-net-cert
  rules:
    - host: komga.internal.gustend.net
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: komga
                port:
                  number: 25600
