apiVersion: v1
kind: Service
metadata:
  name: komga
  labels:
    app.kubernetes.io/name: komga
spec:
  type: ClusterIP
  ports:
    - port: 25600
      targetPort: 25600
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: komga
