apiVersion: apps/v1
kind: Deployment
metadata:
  name: kutt
  labels:
    app.kubernetes.io/name: kutt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kutt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kutt
    spec:
      containers:
        - name: kutt
          image: kutt/kutt:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_FILENAME
              value: "/var/lib/kutt/data.sqlite"
            - name: CUSTOM_DOMAIN_USE_HTTPS
              value: "true"
            - name: DEFAULT_DOMAIN
              value: "lnk.gustend.net"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: kutt-jwt-secret
                  key: JWT_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/kutt
            - name: custom
              mountPath: /kutt/custom
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: kutt-db-data
        - name: custom
          persistentVolumeClaim:
            claimName: kutt-custom
